<?php
  $chambers = array("senate", "house");
  $query = "https://api.propublica.org/congress/v1/115/";
  $results = [];
  $numbers = [];
  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  function getApi ($chamber, $datquery) {
    $ch = curl_init();
    $fullquery = $datquery . $chamber . "/bills/passed.json";
    curl_setopt($ch, CURLOPT_URL, $fullquery);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    $headers = array();
    $headers[] = "X-Api-Key: ng7dbvmURF4yv9GxugL0Z5y61GWWeL2Kawb5zb4P";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $result = curl_exec($ch);

    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
  }
  // End of generated code
  foreach ($chambers as $chamberiteration) {
    $json = json_decode(getApi ($chamberiteration, $query), true);
    echo '<pre>'; print_r($json); echo '</pre>';
    for ($i = 0; $i < count($json['results'][0]['bills']); $i++) {
      $location = $json['results'][0]['bills'][$i];
      $repeat = False;
      if (in_array($location['number'], $numbers)) {
        $repeat = True;
      }
      if ($repeat == False) {
        /* INDEXES: 0 - Bill Number 1 - Bill Title 2 - Bill Summary 3 - Latest Major Action 4 - Latest Major Action Date */
        $results[] = array($location['number'], $location['title'], $location['summary'], $location['latest_major_action'], $location['latest_major_action_date']);
        $numbers[] = $location['number'];
      }
    }
  }
  echo '<pre>'; print_r($results); echo '</pre>';
  //INDEXING SEGMENT
  //This part inputs new bills/bill updates to the local database
?>
